# Numpy 入门

In [2]:
import numpy as np

## nparray实例

In [ ]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


nparray对象的属性
- .ndim  秩
- .shape 行和列数
- .size 个数
- .dtype 元素类型
- .itemsize 每个元素大学，以字节为单位

In [6]:
a.ndim

2

In [7]:
a.shape

(2, 5)

In [8]:
a.size

10

In [9]:
a.dtype

dtype('int32')

In [10]:
a.itemsize

4

## 数组的创建方法

1. 从列表，元组中创建
2. 使用Numpy中函数创建
 - np.arange(n)  使用range()函数，返回nparray类型，元素从0到n-1
 - np.ones(shape) 根据shape生成一个全1数组，shape是元组类型
 - np.zeros(shape) 根据shape生成一个全0数组，shape是元组类型
 - np.full(shape, val) 根据shape生成一个数组，每个元素都是val
 - np.eye(n) 创建一个正方的n*n单位矩阵，对角线为1，其余为0
 - np.ones_like(a) 根据数组a得形状生成一个全1数组
 - np.zeros_like(a) 根据数组a的形状生成一个全0数组
 - np.full_like(a, val) 根据数组a的形状生成一个数组，每个元素都是val
 - np.linspace() 根据起止数据等间距的填充数据，形成新的数组
 - np.concatenate() 将两个或多个数组合并为一个新数组

In [5]:
x = np.array([0, 1, 2, 3])
print(x)

[0 1 2 3]


In [6]:
x = np.array((4, 5, 6, 7))
print(x)

[4 5 6 7]


In [7]:
x = np.array([[1, 2], [9, 8], (0.1, 0.2)])
print(x)

[[ 1.   2. ]
 [ 9.   8. ]
 [ 0.1  0.2]]


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.ones((3, 6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [11]:
np.zeros((3, 6), dtype = np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [12]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
x = np.ones((2, 3, 4))
print(x)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]


In [17]:
x.shape

(2, 3, 4)

In [19]:
a = np.linspace(1, 10, 4)

In [20]:
a 

array([  1.,   4.,   7.,  10.])

In [21]:
b = np.linspace(1, 10, 4, endpoint=False)

In [22]:
b

array([ 1.  ,  3.25,  5.5 ,  7.75])

In [24]:
c = np.concatenate((a, b))

In [25]:
c

array([  1.  ,   4.  ,   7.  ,  10.  ,   1.  ,   3.25,   5.5 ,   7.75])

## 数组的维度变换

- .reshape(shape)  
  不改变数组元素，返回一个shape形状的数组，原数组不变
  
- .resize(shape)与.reshape()功能一致，但修改原数组
  
- .swapaxes(ax1,ax2)
  将数组n个维度中的两个维度进行调换
  
- .flatten()  
  对数组进行降维，返回折叠后的一维数组，原数组不变

In [26]:
a = np.ones((2, 3, 4), dtype=np.int32)

In [27]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [28]:
a.reshape((3, 8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [29]:
a.resize((3, 8))

In [30]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

## 数组类型变换
`new_a = a.astype(new_type)`

**`astype()`方法一定会创建新的数组（原始数据的一个拷贝），即使两个类型一致**

In [32]:
a = np.ones((2, 3, 4), dtype=np.int)

In [33]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [35]:
b = a.astype(np.float)

In [36]:
b

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

## 数组向列表的转换
ls = a.tolist()

In [38]:
a = np.full((2,3,4), 25, dtype=np.int)

In [39]:
a

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]])

In [40]:
a.tolist()

[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]

## 数组索引和切片

### 一维数组的索引和切片与python列表类似

### 多维数组的索引和切片

In [42]:
a = np.arange(24).reshape((2,3,4))

In [43]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
a[1,2,3]

23

In [45]:
a[0,1,2]

6

In [46]:
a[-1, -2, -3]

17

In [47]:
a[:, 1, -3]

array([ 5, 17])

In [50]:
a[:, 1:3,:]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
a[:,:,::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [52]:
a[:,:,:2]

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]])

## NumPy一元函数

np.abs(x) np.fabs(x)  计算数组个元素的绝对值

np.sqrt(x)       平方根

np.square(x)      平方

np.log(x)  np.log10(x)   np.log2(x)      

np.ceil(x)  np.floor(x)

np.rint(x)       四舍五入

np.modf(x)       小数和整数以两个独立数组形式返回

np.cos(x) .cosh  .sin  .sinh  .tan   .tanh

np.exp(x)

np.sign(x)

## NumPy二元函数

```
+ - * / **
np.maximum(x,y) 计算结果为浮点数 np.fmax()
np.minimum(x,y) np.fmin()
np.mod(x,y)
np.copysign(x, y)  将数组y中各元素的值的符号赋值给数组x对应元素
> < >= <= == !=
```